# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

p1 = Pub.create(name: "White Horse 1", email: "aaa@gmail.com", phone: 000-000-000-000, address: "AAAAAAA, BBBB, CCC", postcode: "HD5 5LI", situation: "Our pub has been welcoming punters for over 200 years. We thought we were having a tough time before the virus came along, but now we are fighting for our survival. We really hope we can manage to keep going, and welcome all our loyal customers back soon. Thanks for reading this!
", message_to_supporters: "We are really looking forward to seeing you again soon. Thanks for supporting us in this way! We look forward to serving you our award winning food and local beers as soon as we can. To say thank you, we will include an additional free starter for up to four people when you bring your tickets in to us!", image_pic: "https://www.whitehart-broadoak.co.uk/images/gallery/White_Hart_Cameo_02.jpg")
p2 = Pub.create(name: "White Horse 2", email: "bbb@gmail.com", phone: 111-111-111-111, address: "XXXXXX, QQQ, III", postcode: "HD6 6LI", situation: "Our pub has been welcoming punters for over 200 years. We thought we were having a tough time before the virus came along, but now we are fighting for our survival. We really hope we can manage to keep going, and welcome all our loyal customers back soon. Thanks for reading this!
", message_to_supporters: "We are really looking forward to seeing you again soon. Thanks for supporting us in this way! We look forward to serving you our award winning food and local beers as soon as we can. To say thank you, we will include an additional free starter for up to four people when you bring your tickets in to us!", image_pic: "https://www.whitehart-broadoak.co.uk/images/gallery/White_Hart_Restaurant_01.jpg")
p3 = Pub.create(name: "White Horse 3", email: "ccc@gmail.com", phone: 22222222, address: "LLLLLL, ZZ, DDD", postcode: "HD7 7LI", situation: "Our pub has been welcoming punters for over 200 years. We thought we were having a tough time before the virus came along, but now we are fighting for our survival. We really hope we can manage to keep going, and welcome all our loyal customers back soon. Thanks for reading this!
",  message_to_supporters: "We are really looking forward to seeing you again soon. Thanks for supporting us in this way! We look forward to serving you our award winning food and local beers as soon as we can. To say thank you, we will include an additional free starter for up to four people when you bring your tickets in to us!", image_pic: "https://www.whitehart-broadoak.co.uk/images/gallery/White_Hart_Patio_01.jpg")
p4 = Pub.create(name: "White Horse 4", email: "ddd@gmail.com", phone: 333333, address: "LLLLLL, ZZ, DDD", postcode: "HD7 8LI", situation: "Our pub has been welcoming punters for over 200 years. We thought we were having a tough time before the virus came along, but now we are fighting for our survival. We really hope we can manage to keep going, and welcome all our loyal customers back soon. Thanks for reading this!
",  message_to_supporters: "We are really looking forward to seeing you again soon. Thanks for supporting us in this way! We look forward to serving you our award winning food and local beers as soon as we can. To say thank you, we will include an additional free starter for up to four people when you bring your tickets in to us!", image_pic: "https://www.whitehart-broadoak.co.uk/images/gallery/White_Hart_Patio_07.jpg")
p5 = Pub.create(name: "White Horse 5", email: "eee@gmail.com", phone: 44444, address: "LLLLLL, ZZ, DDD", postcode: "HD7 9LI", situation: "Our pub has been welcoming punters for over 200 years. We thought we were having a tough time before the virus came along, but now we are fighting for our survival. We really hope we can manage to keep going, and welcome all our loyal customers back soon. Thanks for reading this!
",  message_to_supporters: "We are really looking forward to seeing you again soon. Thanks for supporting us in this way! We look forward to serving you our award winning food and local beers as soon as we can. To say thank you, we will include an additional free starter for up to four people when you bring your tickets in to us!", image_pic: "https://www.whitehart-broadoak.co.uk/images/bar-gallery/White_Hart_Bar_07.jpg")
p6 = Pub.create(name: "White Horse 6", email: "fff@gmail.com", phone: 55555, address: "LLLLLL, ZZ, DDD", postcode: "HD7 18LI", situation: "Our pub has been welcoming punters for over 200 years. We thought we were having a tough time before the virus came along, but now we are fighting for our survival. We really hope we can manage to keep going, and welcome all our loyal customers back soon. Thanks for reading this!
",  message_to_supporters: "We are really looking forward to seeing you again soon. Thanks for supporting us in this way! We look forward to serving you our award winning food and local beers as soon as we can. To say thank you, we will include an additional free starter for up to four people when you bring your tickets in to us!", image_pic: "https://www.whitehart-broadoak.co.uk/images/patio/White_Hart_Exterior_01.jpg")
p7 = Pub.create(name: "White Horse 7", email: "qqq@gmail.com", phone: 55555, address: "LLLLLL, ZZ, DDD", postcode: "HD7 17LI", situation: "Our pub has been welcoming punters for over 200 years. We thought we were having a tough time before the virus came along, but now we are fighting for our survival. We really hope we can manage to keep going, and welcome all our loyal customers back soon. Thanks for reading this!
",  message_to_supporters: "We are really looking forward to seeing you again soon. Thanks for supporting us in this way! We look forward to serving you our award winning food and local beers as soon as we can. To say thank you, we will include an additional free starter for up to four people when you bring your tickets in to us!", image_pic: "https://i2-prod.bristolpost.co.uk/incoming/article3348817.ece/ALTERNATES/s810/2_JK_BR_200919coronation-008JPG.jpg")
p8 = Pub.create(name: "White Horse 8", email: "ggg@gmail.com", phone: 55555, address: "LLLLLL, ZZ, DDD", postcode: "HD7 11LI", situation: "Our pub has been welcoming punters for over 200 years. We thought we were having a tough time before the virus came along, but now we are fighting for our survival. We really hope we can manage to keep going, and welcome all our loyal customers back soon. Thanks for reading this!
",  message_to_supporters: "We are really looking forward to seeing you again soon. Thanks for supporting us in this way! We look forward to serving you our award winning food and local beers as soon as we can. To say thank you, we will include an additional free starter for up to four people when you bring your tickets in to us!", image_pic: "http://bullshead.uk.com/wp-content/uploads/2016/01/img_0365.jpg")
p9 = Pub.create(name: "White Horse 9", email: "yyy@gmail.com", phone: 55555, address: "LLLLLL, ZZ, DDD", postcode: "HD7 12LI", situation: "Our pub has been welcoming punters for over 200 years. We thought we were having a tough time before the virus came along, but now we are fighting for our survival. We really hope we can manage to keep going, and welcome all our loyal customers back soon. Thanks for reading this!
",  message_to_supporters: "We are really looking forward to seeing you again soon. Thanks for supporting us in this way! We look forward to serving you our award winning food and local beers as soon as we can. To say thank you, we will include an additional free starter for up to four people when you bring your tickets in to us!", image_pic: "http://bullshead.uk.com/wp-content/uploads/2016/01/img_0346.jpg")
p10 = Pub.create(name: "White Horse 10", email: "zzz@gmail.com", phone: 55555, address: "LLLLLL, ZZ, DDD", postcode: "HD7 15LI", situation: "Our pub has been welcoming punters for over 200 years. We thought we were having a tough time before the virus came along, but now we are fighting for our survival. We really hope we can manage to keep going, and welcome all our loyal customers back soon. Thanks for reading this!
",  message_to_supporters: "We are really looking forward to seeing you again soon. Thanks for supporting us in this way! We look forward to serving you our award winning food and local beers as soon as we can. To say thank you, we will include an additional free starter for up to four people when you bring your tickets in to us!", image_pic: "http://bullshead.uk.com/wp-content/uploads/2014/06/img_0353.jpg")

t1 = Ticket.create(message: "Good luck!!", name:"Dan", email:"dan@test.com", phone: "01342678", address: "aaa", postcode:"Z10 1ZZ", pub_id: p1.id)
t2 = Ticket.create(message: "Would love to support!!!", name:"David", email:"david@test.com", phone: "01343278", address: "aaa", postcode:"Z10 1ZZ", pub_id: p1.id)
t3 = Ticket.create(message: "Can not wait having a drink there again!!", name:"Cathy", email:"cathy@test.com", phone: "01345677", address: "aaa", postcode:"Z10 1ZZ", pub_id: p1.id)
t4 = Ticket.create(message: "Will buy another ticket soon!!", name:"Sophie", email:"sophiem@test.com", phone: "01345679", address: "aaa", postcode:"Z10 1ZZ", pub_id: p1.id)
t5 = Ticket.create(message: "Good luck!!", name:"Tom", email:"tom@test.com", phone: "01345678", address: "aaa", postcode:"Z10 1ZZ", pub_id: p1.id)
t6 = Ticket.create(message: "Good luck!!", name:"Tom", email:"tom@test.com", phone: "01345678", address: "aaa", postcode:"Z10 1ZZ", pub_id: p1.id)
t7 = Ticket.create(message: "Good luck!!", name:"Tom", email:"tom@test.com", phone: "01345678", address: "aaa", postcode:"Z10 1ZZ", pub_id: p1.id)
t8 = Ticket.create(message: "Good luck!!", name:"Tom", email:"tom@test.com", phone: "01345678", address: "aaa", postcode:"Z10 1ZZ", pub_id: p1.id)
t9 = Ticket.create(message: "I look forward to visiting your pub soon!", name:"Tom", email:"tom@test.com", phone: "01345678", address: "aaa", postcode:"Z10 1ZZ", pub_id: p2.id)
t10 = Ticket.create(message: "My pleasure!", name:"Tom", email:"tom@test.com", phone: "01345678", address: "aaa", postcode:"Z10 1ZZ", pub_id: p3.id)
t11 = Ticket.create(message: "Will buy another ticket soon!!", name:"Sophie", email:"sophiem@test.com", phone: "01345679", address: "aaa", postcode:"Z10 1ZZ", pub_id: p4.id)
t12 = Ticket.create(message: "Will buy another ticket soon!!", name:"Sophie", email:"sophiem@test.com", phone: "01345679", address: "aaa", postcode:"Z10 1ZZ", pub_id: p4.id)
t13 = Ticket.create(message: "Will buy another ticket soon!!", name:"Sophie", email:"sophiem@test.com", phone: "01345679", address: "aaa", postcode:"Z10 1ZZ", pub_id: p4.id)
t13 = Ticket.create(message: "I love your pub so I am very happy to support your pub! I will buy more tickets for my friends also! I hope your business will be fine!", name:"Takeshi", email:"takeshim@test.com", phone: "01345989", address: "aaa", postcode:"Z10 1ZZ", pub_id: p1.id)

# # after supporter association completed

# s1 = Supporter.create(name: "Supporter1", email: "hhh@gmail.com", phone: 3, address: "AAAAAAA, BBBB, CCC", postcode: "HD1 5HG")
# s2 = Supporter.create(name: "Supporter2", email: "iiii@gmail.com", phone: 4, address: "XXXXXX, QQQ, III", postcode: "HD2 6HG")
# s1 = Supporter.create(name: "Supporter3", email: "jjj@gmail.com", phone: 5, address: "LLLLLL, ZZ, DDD", postcode: "HD3 7HG")

# t1 = Ticket.create(name: "Ticket1", message: "Good luck!!", pub_id: p1.id, supporter_id: s1.id)
# t2 = Ticket.create(name: "Ticket2", message: "I look forward to visiting your pub soon!", pub_id: p2.id, supporter_id: s2.id)
# t1 = Ticket.create(name: "Ticket3", message: "Mhy pleasure!", pub_id: p3.id, supporter_id: s2.id)